language: php
sudo: required
php:
  - 7.0.15
node_js:
  - 6
services:
  - mysql
  - redis-server
addons:
  hosts:
    - eshopper.app
    - admin.eshopper.app
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install -g gulp
  - composer self-update
  - composer update
  - npm install
  - node -v
  - php --version
  - gulp -v
script:
  - cp .env.travis .env
  - php artisan key:generate
  - sudo chmod -R 777 storage
  - sudo chmod -R 777 bootstrap/cache
  - gulp
  - mysql -e 'create database eshopper'
  - mysql -e 'create database test_eshopper'
  - php artisan migrate
  - php artisan migrate --database=mysql_test
  - ./node_modules/.bin/eslint resources/assets/js
  - ./vendor/bin/phpunit --coverage-text
